[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]
test = "test"
script = "script"
broadcast = "broadcast"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = {key = "${ETHERSCAN_API_KEY}"}
goerli = {key = "${ETHERSCAN_API_KEY}"}
sepolia = {key = "${ETHERSCAN_API_KEY}"}

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
